### ISSUE TITLE
How do clients configure to connect to services in docker?

### ISSUE THREAD

**Issue by lm2024** [minhhungit/mongodb-cluster-docker-compose#10]
I can't connect to the running mongodb through the client, but I can connect in the cmd, how should I configure it?
I am using Win11

**Comment by lm2024** [comment]
I see

**Comment by lephat08** [comment]
Hi, how can I config security for Mongo cluster?

**Comment by minhhungit** [comment]
@lephat08 check this pls https://github.com/minhhungit/mongodb-cluster-docker-compose/tree/master/with-keyfile-auth
