### ISSUE TITLE
Development version

### ISSUE THREAD

**Issue by Dreamwalker666** [minhhungit/mongodb-cluster-docker-compose#13]
Nice work on this.

I was thinking it would also be nice to have a developer version where it only uses 

- 3 x Single node Replicaset 
- 1 config server
- 1 mongos instance

Obviously to mimic prod environment as close as possible.

**Comment by minhhungit** [comment]
hi @Dreamwalker666 there is a mini version here: https://github.com/minhhungit/mongodb-cluster-docker-compose/tree/master/minimize
