### ISSUE TITLE
Error when change image in 'with-keyfile-auth' docker compose file

### ISSUE THREAD

**Issue by channa-zoomi** [minhhungit/mongodb-cluster-docker-compose#16]
I changed the docker image in with-keyfile-auth/docker-compose.yml from jin-mongo:6.0.2 to mongo:5.0.13. Then it throws the below error,

router-01  | {"t":{"$date":"2023-06-26T17:25:52.595+00:00"},"s":"I",  "c":"ACCESS",   "id":20254,   "ctx":"main","msg":"Read security file failed","attr":{"error":{"code":30,"codeName":"InvalidPath","errmsg":"Error reading file /data/mongodb-keyfile: No such file or directory"}}}
router-01  | {"t":{"$date":"2023-06-26T17:25:52.595+00:00"},"s":"F",  "c":"-",        "id":22866,   "ctx":"main","msg":"Error creating service context","attr":{"error":"Location5579201: Unable to acquire security key[s]"}}
router-01  | {"t":{"$date":"2023-06-26T17:25:52.595+00:00"},"s":"I",  "c":"CONTROL",  "id":23138,   "ctx":"main","msg":"Shutting down","attr":{"exitCode":14}}`

Can you help me to figure out the reason for the error

**Comment by minhhungit** [comment]
@channa-zoomi which OS you are using, linux or windows

please follow tutorial (readme.md file) inside folder `/with-keyfile-auth` /https://github.com/minhhungit/mongodb-cluster-docker-compose/tree/master/with-keyfile-auth

it has preparing step: https://github.com/minhhungit/mongodb-cluster-docker-compose/tree/master/with-keyfile-auth#-preparing

**Comment by minhhungit** [comment]
you also might need to remove docker image cache and try again
