### ISSUE TITLE
I got error in getShardDistribution.

### ISSUE THREAD

**Issue by erdinccurebal** [minhhungit/mongodb-cluster-docker-compose#19]
Hi, i got an error like this.

mongos> db.articles.getShardDistribution();
Collection news.articles is not sharded.

**Comment by minhhungit** [comment]
@erdinccurebal I think that's because you have not enable sharding or creating shard key for articles collection, check this step https://github.com/minhhungit/mongodb-cluster-docker-compose#-step-4-enable-sharding-and-setup-sharding-key-

**Comment by erdinccurebal** [comment]
I will try again by making a video, if not, I will share the video with you.
