### ISSUE TITLE
show how to safely take down replicas

### ISSUE THREAD

**Issue by ORESoftware** [minhhungit/mongodb-cluster-docker-compose#3]
It would be nice to see how to safely remove replicas from the cluster.
I only need 1 or 2 replicas in my case. For whatever reason, ChangeStreams seem to work much slower with a lot of replicas?

**Comment by minhhungit** [comment]
@ORESoftware I'm sorry I did not see your message

I am not good at mongodb, I'm also still researching  so I don't have the answer for your question right now

**Comment by minhhungit** [comment]
@ORESoftware 

As I remember mongodb replicas requires 1 primary and at least (2 secondaries) or (1 secondary and 1 arbiter)

Try to check this link if it helps https://www.mongodb.com/docs/v4.4/administration/change-streams-production-recommendations/
