### ISSUE TITLE
use depends_on

### ISSUE THREAD

**Issue by ORESoftware** [minhhungit/mongodb-cluster-docker-compose#4]
in a docker-compose.yml file, you can use: `depends_on` to declare dependencies between containers, which should affect the booting order which may make it more efficient and less error prone:

https://docs.docker.com/compose/compose-file/

**Comment by minhhungit** [comment]
@ORESoftware thank you, I will check it, anyway, a pull request from you will be awesome !

**Comment by ORESoftware** [comment]
for sure

**Comment by minhhungit** [comment]
no longer active
