### ISSUE TITLE
Authentication for cluster

### ISSUE THREAD

**Issue by bao-nguyen-khac** [minhhungit/mongodb-cluster-docker-compose#8]
How can i set username and password for connect to cluster. Set env to all service in docker compose like this ??

router01:
..
    environment:
          MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT
          MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD

**Comment by minhhungit** [comment]
@bao-nguyen-khac I think that way will not work with cluster, I'm working on it, will introduce tutorial to setup cluster on docker with keyfile authentication soon

**Comment by bao-nguyen-khac** [comment]
@minhhungit yeh, i try it and well it's not work. I also so try with keyfile authen but get some error so i look forward tutorial from you

**Comment by minhhungit** [comment]
@bao-nguyen-khac introduced tutorial here https://github.com/minhhungit/mongodb-cluster-docker-compose/tree/master/with-keyfile-auth

Please check and let me know if you have any question

**Comment by bao-nguyen-khac** [comment]
@minhhungit Nice it work well

**Comment by samuelpares** [comment]
Is step 5 needed for all databases and collections?
In a multitenant app where each tenant has his own database, how could I make it work?

**Comment by minhhungit** [comment]
@samuelpares step 5 defind how to enable sharding and create shardkey for a collection of one database, so if you have new database and need to shard, you also need to do it 

I don't have much exp with  multiple tenancy app and mongodb, but I think after you create an user you can write code to create new database and shard it, like this:

https://stackoverflow.com/a/56297175/3007147
